name: CITEX
on:
  push:
    branches:
      - main
      - 03-draft-paper
      - 05-submitted-version
      - 08-camera-ready

jobs:
  build:
    if: "contains(github.event.head_commit.message, 'CITEX')"
    runs-on: ubuntu-latest
    steps:

    - name: Set up Git repository
      uses: actions/checkout@v1

    - name: Compile LaTeX
      uses: xu-cheng/latex-action@v2
      with:
        root_file: main.tex
        working_directory: article/latex

    - name: Check pdf files
      run: |
        file article/latex/main.pdf | grep -q ' PDF '
 
    - name: Upload pdf to pdfs branch
      run: |
        # configure git
        git config --global user.name "mxochicale"
        git config --global user.email "perez.xochicale@gmail.com"
        # setup ssh
        mkdir ~/.ssh
        chmod 700 ~/.ssh
        echo "$DEPLOY_KEY" > ~/.ssh/id_rsa
        chmod 600 ~/.ssh/id_rsa
        git config --global core.sshCommand "ssh -i ~/.ssh/id_rsa -o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no"
        git clone --depth=1 --branch pdfs git@github.com:air4children/hri2023.git "$GITHUB_WORKSPACE/deploy"
        cp -f article/latex/main.pdf "$GITHUB_WORKSPACE/deploy/paper.pdf"
        cd "$GITHUB_WORKSPACE/deploy"
        git add paper.pdf 
        git commit -m "latex-action deploy"
        git push
      env:
        DEPLOY_KEY: ${{ secrets.DEPLOY_KEY }}
