name: Compiling-TeX-Slides
on:
  push:
    branches:
      - no-main
      - 11-slides
      - 16-slides-spanish
      - adds-branch-name

jobs:
  build:
    if: "!contains(github.event.head_commit.message, '[skip-slides]') && !contains(github.event.head_commit.message, '[skip-all]')"
    runs-on: ubuntu-latest
    steps:

    - name: Set up Git repository
      uses: actions/checkout@v3

    - name: Compile Slides
      uses: xu-cheng/latex-action@v2
      with:
        root_file: main.tex
        working_directory: slides/slides-espanol/

    - name: Check pdf files
      run: |
        file slides/slides-espanol/main.pdf | grep -q ' PDF '
 
    - name: Upload
      run: |
        # configure git
        git config --global user.name "mxochicale"
        git config --global user.email "perez.xochicale@gmail.com"
        # setup ssh
        mkdir ~/.ssh
        chmod 700 ~/.ssh
        echo "$DEPLOY_KEY" > ~/.ssh/id_rsa
        chmod 600 ~/.ssh/id_rsa
        git config --global core.sshCommand "ssh -i ~/.ssh/id_rsa -o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no"
        git clone --depth=1 --branch pdfs git@github.com:air4children/dei-hri2023.git "$GITHUB_WORKSPACE/deploy"
        cp -f slides/slides-espanol/main.pdf "$GITHUB_WORKSPACE/deploy/slides-espanol.pdf"
        cd "$GITHUB_WORKSPACE/deploy"
        git add slides-espanol.pdf 
        git commit -m "latex-action deploy"
        git push
      env:
        DEPLOY_KEY: ${{ secrets.DEPLOY_KEY }}
